### ISSUE TITLE
App doens't work over https

### ISSUE THREAD

**Issue by tommytusj** [enonic/app-xphoot#9] opened 2017-02-28 21:38 UTC
Seems like there is references to ws:// that gives this error when using https

`Mixed Content: The page at 'https://xphoot.no/player' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://xphoot/_/service/com.enonic.app.xphoot/gameHub'. This request has been blocked; this endpoint must be available over WSS.`

**Comment by aro** [comment] 2017-03-02 08:40
I think the problem is when there is a front-end server (e.g. Apache) serving on HTTPS and XP behind on HTTP. I did not consider this case.
Thanks for reporting this. We will look into it.

**Comment by runarmyklebust** [comment] 2017-03-10 08:28
Nice!

**Comment by aro** [comment] 2017-03-10 08:40
@tommytusj We have just released a new version with a fix for this issue. It should now detect if the connection is over HTTPS and use the WSS protocol, instead of WS.
https://github.com/enonic/app-xphoot/releases/tag/v1.3.1

It is also available in Enonic market.

Note that if you have a proxy/load-balancer in front of XP handling the HTTPS connection, it should add an HTTP header in the forwarded request, so that XP knows the client connection is over HTTPS: `X-Forwarded-Proto: https`

See [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto)

**Closed by aro** 2017-03-10 08:40 UTC
Labels: bug
